# Generated by Django 4.2.3 on 2023-12-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_alter_exerciselog_exercise_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='user',
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health.userprofile'),
        ),
    ]
